name=Resistive_Sensor
version=1.1.0
author=FOURNET Olivier
email=olivier.fournet@free.fr
maintainer=FOURNET Olivier
sentence=Bibliothèque Arduino pour_capteur résistif d'humidité du sol (fils de cuivre)
paragraph=Calcule la résistance du sol et le pourcentage d'humidité à partir d'un_capteur résistif (fils de cuivre). Inclut les fonctions de conversion tension->résistance et résistance->humidité.
url=https://github.com/Fo170/Resistive_Sensor
categories=Sensors
architectures=*
source_dir=src
includes=ResistiveSoilSensor.h