; PlatformIO Project Configuration File
;
; Please visit documentation https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    ResistiveSoilSensor

[env:nodemcu]
platform = esp8266
board = nodemcu
framework = arduino
monitor_speed = 115200
lib_deps =
    ResistiveSoilSensor

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    ResistiveSoilSensor

[env:esp32-s2]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
lib_deps =
    ResistiveSoilSensor

[env:stm32]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
monitor_speed = 115200
lib_deps =
    ResistiveSoilSensor
